const API=(localStorage.getItem("meetwise_api")||"http://localhost:4000/api").replace(/\/$/,"");
const S={token:localStorage.getItem("meetwise_token"),user:JSON.parse(localStorage.getItem("meetwise_user")||"null"),meetup:null,memberId:localStorage.getItem("meetwise_member")};
async function api(p,o={}){const h={"Content-Type":"application/json",...(o.headers||{})};if(S.token)h.Authorization="Bearer "+S.token;const r=await fetch(API+p,{...o,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
const save=d=>{S.token=d.token;S.user=d.user;localStorage.setItem("meetwise_token",d.token);localStorage.setItem("meetwise_user",JSON.stringify(d.user))};
function esc(x){return String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function auth(){app.innerHTML='<main class="shell"><div class="brand">MeetWise AI</div><div class="grid"><section class="card"><h1>Plan together. Smarter.</h1><p class="muted">AI researches real places, travel and weather for your group.</p><input id="sn" placeholder="Name"><input id="se" placeholder="Email"><input id="sp" type="password" placeholder="Password (8+ characters)"><button onclick="signup()">Create account</button></section><section class="card"><h2>Log in</h2><input id="le" placeholder="Email"><input id="lp" type="password" placeholder="Password"><button onclick="login()">Log in</button><p id="msg"></p></section></div></main>'}
async function signup(){try{save(await api("/auth/signup",{method:"POST",body:JSON.stringify({name:sn.value,email:se.value,password:sp.value})}));home()}catch(e){msg.textContent=e.message}}
async function login(){try{save(await api("/auth/login",{method:"POST",body:JSON.stringify({email:le.value,password:lp.value})}));home()}catch(e){msg.textContent=e.message}}
function home(){app.innerHTML='<main class="shell"><div class="nav"><b class="brand">MeetWise AI</b><button class="secondary" style="width:auto" onclick="logout()">Log out</button></div><div class="grid"><section class="card"><h2>Create meetup</h2><input id="mt" placeholder="Saturday evening meetup"><button onclick="create()">Create & invite</button></section><section class="card"><h2>Join meetup</h2><input id="mc" placeholder="Invite code"><input id="jn" placeholder="Your name"><button onclick="join()">Join</button></section></div></main>'}
async function create(){try{S.meetup=await api("/meetups",{method:"POST",body:JSON.stringify({title:mt.value,organizerName:S.user.name})});S.memberId=S.meetup.organizerId;localStorage.setItem("meetwise_member",S.memberId);dash()}catch(e){alert(e.message)}}
async function join(){try{const m=await api("/meetups/code/"+encodeURIComponent(mc.value));const x=await api("/meetups/"+m.id+"/join",{method:"POST",body:JSON.stringify({name:jn.value||S.user.name,inviteCode:m.inviteCode})});S.meetup=await api("/meetups/"+m.id);S.memberId=x.id;localStorage.setItem("meetwise_member",x.id);dash()}catch(e){alert(e.message)}}
function dash(){const m=S.meetup;app.innerHTML='<main class="shell"><div class="nav"><div><b class="brand">MeetWise AI</b><div class="muted">'+esc(m.title)+'</div></div><span class="pill">Invite: <b>'+m.inviteCode+'</b></span></div><div class="grid"><section class="card"><h3>Members</h3><div id="members"></div><h3>Your constraints</h3><input id="area" placeholder="Area / neighborhood"><select id="tr"><option value="">Transport</option><option>walking</option><option>bike</option><option>car</option><option>public_transport</option></select><input id="budget" type="number" placeholder="Budget PKR"><input id="max" type="number" placeholder="Max travel minutes"><input id="food" placeholder="Food, comma separated"><input id="act" placeholder="Activities, comma separated"><input id="when" type="datetime-local"><button onclick="prefs()">Save preferences</button><button class="secondary" onclick="plan()">Research live options</button><button class="secondary" onclick="replan()">Re-plan</button></section><section class="card"><h3>Group chat</h3><div id="chat" class="chat"></div><div class="row"><input id="ct" placeholder="New constraint or message"><button style="max-width:120px" onclick="send()">Send</button></div><button class="secondary" onclick="analyze()">AI constraint analysis</button><pre id="ai" style="white-space:pre-wrap"></pre></section></div><section class="card" style="margin-top:18px"><h2>AI Meetup Plan</h2><div id="results">Add locations and preferences first.</div><div id="votes" class="muted"></div></section></main>';refresh()}
async function refresh(){S.meetup=await api("/meetups/"+S.meetup.id);members.innerHTML=S.meetup.members.map(m=>'<span class="pill">'+esc(m.name)+'</span>').join("");chat.innerHTML=S.meetup.chat.map(x=>'<div class="msg"><b>'+esc(S.meetup.members.find(m=>m.id===x.memberId)?.name||"Member")+'</b>: '+esc(x.text)+'</div>').join("")}
async function prefs(){const p={area:area.value,transportMode:tr.value||undefined,budget:Number(budget.value)||undefined,maxTravelMinutes:Number(max.value)||undefined,foodPreferences:food.value.split(",").map(x=>x.trim()).filter(Boolean),activityPreferences:act.value.split(",").map(x=>x.trim()).filter(Boolean),availableFrom:when.value||undefined};try{await api("/meetups/"+S.meetup.id+"/members/"+S.memberId+"/preferences",{method:"PATCH",body:JSON.stringify(p)});await refresh();alert("Saved. Run research or re-plan.")}catch(e){alert(e.message)}}
async function plan(){try{show(await api("/live/meetups/"+S.meetup.id+"/plan",{method:"POST",body:JSON.stringify({when:when.value||undefined})}))}catch(e){alert(e.message)}}
async function replan(){try{const d=await api("/meetups/"+S.meetup.id+"/replan",{method:"POST",body:JSON.stringify({reason:"A member changed a constraint",memberId:S.memberId,when:when.value||undefined})});show(d.plan)}catch(e){alert(e.message)}}
function show(d){if(d.status!=="ready"){results.innerHTML="<p>"+esc(d.status)+"</p>";return}results.innerHTML=d.candidates.map((x,i)=>'<div class="candidate"><div class="score">Option '+(i+1)+' · '+(x.score===null?"Verified score unavailable":x.score+"% verified constraints")+'</div><b>'+esc(x.candidate.name)+'</b><p class="muted">'+esc(x.candidate.address)+'</p><p>'+x.travel.map(t=>{const n=S.meetup.members.find(m=>m.id===t.memberId)?.name||"Member";return '<span class="pill">'+esc(n)+": "+(t.durationMinutes??"unknown")+" min</span>"}).join("")+'</p><p>'+x.explanation.map(esc).join(" · ")+'</p><p class="muted">'+esc(x.budgetStatus)+'</p><button onclick="vote(\''+String(x.candidate.id).replace(/'/g,"\\'")+'\')">Vote for this option</button></div>').join("")}
async function vote(id){try{await api("/meetups/"+S.meetup.id+"/votes",{method:"POST",body:JSON.stringify({memberId:S.memberId,optionId:id})});await voteSummary();alert("Vote recorded")}catch(e){alert(e.message)}}
async function voteSummary(){try{const d=await api("/meetups/"+S.meetup.id+"/votes");votes.textContent=d.counts.length?"Votes: "+d.counts.map(x=>x.optionId+" = "+x.votes).join(" · "):"No votes yet"}catch{}}
async function send(){if(!ct.value.trim())return;try{const d=await api("/meetups/"+S.meetup.id+"/chat",{method:"POST",body:JSON.stringify({memberId:S.memberId,text:ct.value})});ct.value="";if(d.aiAnalysis?.available){ai.textContent=typeof d.aiAnalysis.result==="string"?d.aiAnalysis.result:JSON.stringify(d.aiAnalysis.result,null,2)}await refresh()}catch(e){alert(e.message)}}
async function analyze(){try{const d=await api("/live/meetups/"+S.meetup.id+"/analyze",{method:"POST"});ai.textContent=typeof d.result==="string"?d.result:JSON.stringify(d.result,null,2)}catch(e){ai.textContent=e.message}}
async function logout(){try{await api("/auth/logout",{method:"POST"})}catch{}localStorage.clear();location.reload()}
if(S.token&&S.user)home();else auth();