const app=document.getElementById("app");
const API=(localStorage.getItem("meetwise_api")||"https://meetwise-backend.vercel.app/api").replace(/\/$/,"");
const S={token:localStorage.getItem("meetwise_token"),user:JSON.parse(localStorage.getItem("meetwise_user")||"null"),meetup:null,memberId:localStorage.getItem("meetwise_member")};
async function api(p,o={}){const h={"Content-Type":"application/json",...(o.headers||{})};if(S.token)h.Authorization="Bearer "+S.token;const r=await fetch(API+p,{...o,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
const save=d=>{S.token=d.token;S.user=d.user;localStorage.setItem("meetwise_token",d.token);localStorage.setItem("meetwise_user",JSON.stringify(d.user))};
function esc(x){return String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function auth(){app.innerHTML='<main class="shell"><div class="brand">MeetWise AI</div><div class="grid"><section class="card"><h1>Plan together. Smarter.</h1><p class="muted">AI researches real places, travel and weather for your group.</p><input id="sn" placeholder="Name"><input id="se" placeholder="Email"><input id="sp" type="password" placeholder="Password (8+ characters)"><button onclick="signup()">Create account</button></section><section class="card"><h2>Log in</h2><input id="le" placeholder="Email"><input id="lp" type="password" placeholder="Password"><button onclick="login()">Log in</button><p id="msg"></p></section></div></main>'}
async function signup(){try{save(await api("/auth/signup",{method:"POST",body:JSON.stringify({name:sn.value,email:se.value,password:sp.value})}));home()}catch(e){msg.textContent=e.message}}
async function login(){try{save(await api("/auth/login",{method:"POST",body:JSON.stringify({email:le.value,password:lp.value})}));home()}catch(e){msg.textContent=e.message}}
function home(){app.innerHTML='<main class="shell"><div class="nav"><b class="brand">MeetWise AI</b><button class="secondary" style="width:auto" onclick="logout()">Log out</button></div><div class="grid"><section class="card"><h2>Create meetup</h2><input id="mt" placeholder="Saturday evening meetup"><button onclick="create()">Create & invite</button></section><section class="card"><h2>Join meetup</h2><input id="mc" placeholder="Invite code"><input id="jn" placeholder="Your name"><button onclick="join()">Join</button></section></div></main>"}
async function create(){try{S.meetup=await api("/meetups",{method:"POST",body:JSON.stringify({title:mt.value,organizerName:S.user.name})});S.memberId=S.meetup.organizerId;localStorage.setItem("meetwise_member",S.memberId);dash()}catch(e){alert(e.message)}}
async function join(){try{const m=await api("/meetups/code/"+encodeURIComponent(mc.value));const x=await api("/meetups/"+m.id+"/join",{method:"POST",body:JSON.stringify({name:jn.value||S.user.name,inviteCode:m.inviteCode})});S.meetup=await api("/meetups/"+m.id);S.memberId=x.id;localStorage.setItem("meetwise_member",x.id);dash()}catch(e){alert(e.message)}}
function dash(){const m=S.meetup;app.innerHTML='<main class="shell"><div class="nav"><div><b class="brand">MeetWise AI</b><div class="muted">'+esc(m.title)+'</div></div><span class="pill">Invite: <b>'+esc(m.inviteCode)+'</b></span></div><div class="grid"><section class="card"><h3>Members</h3><div id="members"></div><h3>Your constraints</h3><input id="area" placeholder="Area / neighborhood"><select id="tr"><option value="">Transport</option><option>walking</option><option>bike</option><option>car</option><option>public_transport</option></select><input id="budget" type="number" placeholder="Budget PKR"><input id="max" type="number" placeholder="Max travel minutes"><input id="food" placeholder="Food, comma separated"><input id="act" placeholder="Activities, comma separated"><input id="when" type="datetime-local"><button onclick="prefs()">Save preferences</button><button class="secondary" onclick="plan()">Research live options</button><button class="secondary" onclick="replan()">Re-plan</button><p id="planStatus" class="muted"></p></section><section class="card"><h3>Group chat</h3><div id="chat" class="chat"></div><div class="row"><input id="ct" placeholder="New constraint or message"><button style="max-width:120px" onclick="send()">Send</button></div><button class="secondary" onclick="analyze()">AI constraint analysis</button><pre id="ai" style="white-space:pre-wrap"></pre></section></div><section class="card" style="margin-top:18px"><div class="nav"><div><h2 style="margin:0">AI Meetup Plan</h2><p class="muted" style="margin:4px 0 0">Live research + constraint reasoning</p></div><span id="planBadge" class="pill">Not researched</span></div><div id="results"><div class="emptyState"><b>Ready to research</b><p>Save at least one member's area and preferences, then run live research.</p></div></div><div id="votes" class="muted"></div></section></main>';refresh()}
async function refresh(){S.meetup=await api("/meetups/"+S.meetup.id);renderMembersAndChat();prefill();await voteSummary()}
function renderMembersAndChat(){members.innerHTML=S.meetup.members.map(m=>{const p=m.preferences||{};const ready=!!(p.area||(p.foodPreferences||[]).length||(p.activityPreferences||[]).length);return '<span class="pill '+(ready?"pillReady":"")+'">'+esc(m.name)+(ready?" ✓":" · preferences pending")+'</span>'}).join("");chat.innerHTML=S.meetup.chat.map(x=>'<div class="msg"><b>'+esc(S.meetup.members.find(m=>m.id===x.memberId)?.name||"Member")+'</b>: '+esc(x.text)+'</div>').join("");chat.scrollTop=chat.scrollHeight}
function prefill(){const m=S.meetup?.members.find(x=>x.id===S.memberId),p=m?.preferences||{};if(!m)return;area.value=p.area||"";tr.value=p.transportMode||"";budget.value=p.budget??"";max.value=p.maxTravelMinutes??"";food.value=(p.foodPreferences||[]).join(", ");act.value=(p.activityPreferences||[]).join(", ");when.value=p.availableFrom||""}
async function pollChat(){try{const latest=await api("/meetups/"+S.meetup.id);const changed=latest.chat.length!==S.meetup.chat.length||latest.members.length!==S.meetup.members.length;if(changed){S.meetup=latest;renderMembersAndChat();prefill()}}catch{}}
async function prefs(){const p={area:area.value.trim(),transportMode:tr.value||undefined,budget:Number(budget.value)||undefined,maxTravelMinutes:Number(max.value)||undefined,foodPreferences:food.value.split(",").map(x=>x.trim()).filter(Boolean),activityPreferences:act.value.split(",").map(x=>x.trim()).filter(Boolean),availableFrom:when.value||undefined};try{planStatus.textContent="Saving…";await api("/meetups/"+S.meetup.id+"/members/"+S.memberId+"/preferences",{method:"PATCH",body:JSON.stringify(p)});await refresh();planStatus.textContent="Preferences saved. Run live research when everyone has joined.";alert("Preferences saved")}catch(e){planStatus.textContent="";alert(e.message)}}
async function plan(){try{planBadge.textContent="Researching…";planStatus.textContent="AI is researching places, travel and weather…";results.innerHTML='<div class="loading">Researching live options…</div>';show(await api("/live/meetups/"+S.meetup.id+"/plan",{method:"POST",body:JSON.stringify({when:when.value||undefined})}));planStatus.textContent="Research complete."}catch(e){planBadge.textContent="Error";planStatus.textContent="";results.innerHTML='<div class="errorBox">'+esc(e.message)+'</div>'}}
async function replan(){try{planBadge.textContent="Re-planning…";planStatus.textContent="A constraint changed — recalculating the meetup plan…";const d=await api("/meetups/"+S.meetup.id+"/replan",{method:"POST",body:JSON.stringify({reason:"A member changed a constraint",memberId:S.memberId,when:when.value||undefined})});show(d.plan);planStatus.textContent="Re-plan complete."}catch(e){planBadge.textContent="Error";planStatus.textContent="";results.innerHTML='<div class="errorBox">'+esc(e.message)+'</div>'}}
function show(d){if(d.status==="needs_input"){planBadge.textContent="Needs input";results.innerHTML='<div class="emptyState"><b>More group information is needed</b><p>'+esc((d.missingData||[]).join(", "))+'</p><p>Save the location/preferences for at least one member, then run research again.</p></div>';return}if(d.status==="no_results"){planBadge.textContent="No live matches";results.innerHTML='<div class="emptyState"><b>No suitable live places were found.</b><p>Try a broader area or simpler activity/food preferences.</p></div>';return}if(d.status!=="ready"){planBadge.textContent="Unavailable";results.innerHTML="<p>"+esc(d.status||"Planning unavailable")+"</p>";return}planBadge.textContent=(d.candidates?.length||0)+" options";const intro='<div class="planMeta"><span class="pill">Goal: '+esc(d.goal)+'</span><span class="pill">Source: '+esc(d.source)+'</span></div><p class="muted">'+esc(d.objective||"Meetup constraints were evaluated from available live data.")+'</p>';results.innerHTML=intro+(d.candidates||[]).map((x,i)=>{const weather=x.weather?.available?'<p class="weather"><b>Weather:</b> '+esc(x.weather.summary||"Forecast available")+(x.weather.precipitationProbability!=null?" · Rain probability "+esc(x.weather.precipitationProbability)+"%":"")+'</p>':"";const travel=(x.travel||[]).map(t=>{const n=S.meetup.members.find(m=>m.id===t.memberId)?.name||"Member";return '<span class="pill">'+esc(n)+": "+(t.durationMinutes??"unknown")+" min</span>"}).join("");return '<div class="candidate"><div class="score">Option '+(i+1)+' · '+(x.score===null?"Verified score unavailable":x.score+"% verified constraints")+'</div><h3>'+esc(x.candidate.name)+'</h3><p class="muted">'+esc(x.candidate.address)+'</p><p>'+travel+'</p>'+weather+'<p>'+x.explanation.map(esc).join(" · ")+'</p><p class="muted">'+esc(x.budgetStatus)+'</p><button onclick="vote(\''+String(x.candidate.id).replace(/'/g,"\\'")+'\')">Vote for this option</button></div>"}).join("")+(d.limitations?.length?'<details class="muted"><summary>Research limitations</summary><ul>'+d.limitations.map(x=>"<li>"+esc(x)+"</li>").join("")+"</ul></details>":"")}
async function vote(id){try{await api("/meetups/"+S.meetup.id+"/votes",{method:"POST",body:JSON.stringify({memberId:S.memberId,optionId:id})});await voteSummary();alert("Vote recorded")}catch(e){alert(e.message)}}
async function voteSummary(){try{const d=await api("/meetups/"+S.meetup.id+"/votes");votes.textContent=d.counts.length?"Votes: "+d.counts.map(x=>x.optionId+" = "+x.votes).join(" · "):"No votes yet"}catch{votes.textContent=""}}
async function send(){if(!ct.value.trim())return;try{const d=await api("/meetups/"+S.meetup.id+"/chat",{method:"POST",body:JSON.stringify({memberId:S.memberId,text:ct.value})});ct.value="";if(d.aiAnalysis?.available){ai.textContent=typeof d.aiAnalysis.result==="string"?d.aiAnalysis.result:JSON.stringify(d.aiAnalysis.result,null,2)}await refresh()}catch(e){alert(e.message)}}
async function analyze(){try{const d=await api("/live/meetups/"+S.meetup.id+"/analyze",{method:"POST"});ai.textContent=typeof d.result==="string"?d.result:JSON.stringify(d.result,null,2)}catch(e){ai.textContent=e.message}}
async function logout(){try{await api("/auth/logout",{method:"POST"})}catch{}localStorage.clear();location.reload()}
if(S.token&&S.user){home();setInterval(pollChat,3000)}else auth();